/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    floor006: THREE.Mesh;
    shadeBrown025: THREE.Mesh;
    shadeBrown007: THREE.Mesh;
    shadeBrown026: THREE.Mesh;
    shadeBrown008: THREE.Mesh;
    shadeBrown012: THREE.Mesh;
    shadeBrown013: THREE.Mesh;
    shadeBrown014: THREE.Mesh;
    shadeBrown017: THREE.Mesh;
    shadeBrown020: THREE.Mesh;
    shadeBrown021: THREE.Mesh;
    shadeBrown019: THREE.Mesh;
    shadeBrown022: THREE.Mesh;
    shadeBrown023: THREE.Mesh;
    shadeBrown027: THREE.Mesh;
    shadeBrown024: THREE.Mesh;
    shadeBrown028: THREE.Mesh;
    shadeBrown029: THREE.Mesh;
    shadeBrown032: THREE.Mesh;
    shadeBrown030: THREE.Mesh;
    shadeBrown031: THREE.Mesh;
    shadeBrown033: THREE.Mesh;
    shadeBrown036: THREE.Mesh;
    shadeBrown035: THREE.Mesh;
    shadeBrown034: THREE.Mesh;
    shadeBrown037: THREE.Mesh;
    shadeBrown040: THREE.Mesh;
    shadeBrown039: THREE.Mesh;
    shadeBrown038: THREE.Mesh;
    shadeBrown041: THREE.Mesh;
    shadeBrown044: THREE.Mesh;
    shadeBrown043: THREE.Mesh;
    shadeBrown042: THREE.Mesh;
    shadeBrown045: THREE.Mesh;
    shadeBrown048: THREE.Mesh;
    shadeBrown047: THREE.Mesh;
    shadeBrown046: THREE.Mesh;
    shadeBrown050: THREE.Mesh;
    shadeBrown055: THREE.Mesh;
    shadeBrown052: THREE.Mesh;
    shadeBrown051: THREE.Mesh;
    shadeBrown053: THREE.Mesh;
    shadeGreen007: THREE.Mesh;
    shadeGreen003: THREE.Mesh;
    shadeBrown054: THREE.Mesh;
    shadeGreen004: THREE.Mesh;
    shadeWhite_002002: THREE.Mesh;
    shadeGreen009: THREE.Mesh;
    shadeGreen005: THREE.Mesh;
    shadeGreen010: THREE.Mesh;
    shadeWhite_015008: THREE.Mesh;
    shadeWhite_003003: THREE.Mesh;
    shadeWhite_001002: THREE.Mesh;
    shadeWhite_004001: THREE.Mesh;
    shadeWhite_015019: THREE.Mesh;
    shadeWhite_002003: THREE.Mesh;
    shadeWhite_015006: THREE.Mesh;
    shadeWhite_015022: THREE.Mesh;
    shadeWhite_015023: THREE.Mesh;
    shadeBrown_023: THREE.Mesh;
    shadeWhite_015018: THREE.Mesh;
    shadeWhite_015025: THREE.Mesh;
    shadeWhite_015021: THREE.Mesh;
    shadeBrown_020001: THREE.Mesh;
    shadeWhite_015020: THREE.Mesh;
    shadeBrown_018: THREE.Mesh;
    shadeBrown_019: THREE.Mesh;
    shadeBeige_002: THREE.Mesh;
    shadeWhite_015024: THREE.Mesh;
    shadeBrown_021: THREE.Mesh;
    shadeBrown_022: THREE.Mesh;
    shadeBeige_003: THREE.Mesh;
    shadeBeige_001: THREE.Mesh;
    shadeBrown_018001: THREE.Mesh;
    shadeBrown_019001: THREE.Mesh;
    shadeBrown_015002: THREE.Mesh;
    shadeBrown_020: THREE.Mesh;
    shadeBrown_022001: THREE.Mesh;
    shadeBrown_014001: THREE.Mesh;
    shadeBrown_017006: THREE.Mesh;
    shadeBrown_014: THREE.Mesh;
    shadeBrown_017003: THREE.Mesh;
    shadeBrown_017004: THREE.Mesh;
    shadeBrown_017010: THREE.Mesh;
    shadeBrown_021001: THREE.Mesh;
    shadeBeige_006: THREE.Mesh;
    shadeBrown_015001: THREE.Mesh;
    shadeBrown_017012: THREE.Mesh;
    shadeBrown_017002: THREE.Mesh;
    shadeBrown_017005: THREE.Mesh;
    shadeBrown_015004: THREE.Mesh;
    shadeBeige_009: THREE.Mesh;
    shadeBeige_005: THREE.Mesh;
    shadeBrown_017008: THREE.Mesh;
    shadeBrown_017009: THREE.Mesh;
    shadeBrown_015008: THREE.Mesh;
    shadeBrown_015003: THREE.Mesh;
    shadeBrown_016002: THREE.Mesh;
    shadeBrown_017011: THREE.Mesh;
    shadeBrown_017017: THREE.Mesh;
    shadeBrown_017007: THREE.Mesh;
    shadeBeige_008: THREE.Mesh;
    shadeBeige_007: THREE.Mesh;
    shadeBrown_016004: THREE.Mesh;
    shadeBrown_016001: THREE.Mesh;
    shadeBrown_015007: THREE.Mesh;
    shadeBrown_015006: THREE.Mesh;
    shadeBrown059: THREE.Mesh;
    shadeBrown_017013: THREE.Mesh;
    shadeBrown_017016: THREE.Mesh;
    shadeBrown_017015: THREE.Mesh;
    shadeBrown_015005: THREE.Mesh;
    shadeBrown_016003: THREE.Mesh;
    shadeBrown_017019: THREE.Mesh;
    shadeBrown_017014: THREE.Mesh;
    shadeRed_004: THREE.Mesh;
    shadeRed_003: THREE.Mesh;
    shadeBrown_017018: THREE.Mesh;
    shadeBeige: THREE.Mesh;
  };
  materials: {};
};

export default function Playground(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/static/base.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.floor006.geometry}
        material={nodes.floor006.material}
        scale={40}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown025.geometry}
        material={nodes.shadeBrown025.material}
        position={[1.72, 7.57, 0.62]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown007.geometry}
        material={nodes.shadeBrown007.material}
        position={[3.14, 7.7, -0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown026.geometry}
        material={nodes.shadeBrown026.material}
        position={[0.3, 7.7, -0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown008.geometry}
        material={nodes.shadeBrown008.material}
        position={[5.56, 7.57, 0.62]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown012.geometry}
        material={nodes.shadeBrown012.material}
        position={[6.98, 7.7, -0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown013.geometry}
        material={nodes.shadeBrown013.material}
        position={[4.14, 7.7, -0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown014.geometry}
        material={nodes.shadeBrown014.material}
        position={[9.42, 7.57, 0.62]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown017.geometry}
        material={nodes.shadeBrown017.material}
        position={[10.84, 7.7, -0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown020.geometry}
        material={nodes.shadeBrown020.material}
        position={[9.42, 0.46, 0.62]}
        rotation={[0, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown021.geometry}
        material={nodes.shadeBrown021.material}
        position={[8, 0.33, -0.25]}
        rotation={[0, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown019.geometry}
        material={nodes.shadeBrown019.material}
        position={[8, 7.7, -0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown022.geometry}
        material={nodes.shadeBrown022.material}
        position={[10.84, 0.33, -0.25]}
        rotation={[0, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown023.geometry}
        material={nodes.shadeBrown023.material}
        position={[5.57, 0.46, 0.62]}
        rotation={[0, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown027.geometry}
        material={nodes.shadeBrown027.material}
        position={[7, 0.33, -0.25]}
        rotation={[0, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown024.geometry}
        material={nodes.shadeBrown024.material}
        position={[4.16, 0.33, -0.25]}
        rotation={[0, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown028.geometry}
        material={nodes.shadeBrown028.material}
        position={[1.72, 0.46, 0.62]}
        rotation={[0, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown029.geometry}
        material={nodes.shadeBrown029.material}
        position={[0.3, 0.33, -0.25]}
        rotation={[0, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown032.geometry}
        material={nodes.shadeBrown032.material}
        position={[-0.74, 7.7, -0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown030.geometry}
        material={nodes.shadeBrown030.material}
        position={[3.14, 0.33, -0.25]}
        rotation={[0, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown031.geometry}
        material={nodes.shadeBrown031.material}
        position={[-2.16, 7.57, 0.62]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown033.geometry}
        material={nodes.shadeBrown033.material}
        position={[-3.58, 7.7, -0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown036.geometry}
        material={nodes.shadeBrown036.material}
        position={[-0.74, 0.33, -0.25]}
        rotation={[0, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown035.geometry}
        material={nodes.shadeBrown035.material}
        position={[-3.58, 0.33, -0.25]}
        rotation={[0, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown034.geometry}
        material={nodes.shadeBrown034.material}
        position={[-2.16, 0.46, 0.62]}
        rotation={[0, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown037.geometry}
        material={nodes.shadeBrown037.material}
        position={[-6.09, 7.57, 0.62]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown040.geometry}
        material={nodes.shadeBrown040.material}
        position={[-6.09, 0.46, 0.62]}
        rotation={[0, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown039.geometry}
        material={nodes.shadeBrown039.material}
        position={[-7.51, 7.7, -0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown038.geometry}
        material={nodes.shadeBrown038.material}
        position={[-4.67, 7.7, -0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown041.geometry}
        material={nodes.shadeBrown041.material}
        position={[-7.51, 0.33, -0.25]}
        rotation={[0, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown044.geometry}
        material={nodes.shadeBrown044.material}
        position={[-8.6, 7.7, -0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown043.geometry}
        material={nodes.shadeBrown043.material}
        position={[-10.02, 7.57, 0.62]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown042.geometry}
        material={nodes.shadeBrown042.material}
        position={[-4.67, 0.33, -0.25]}
        rotation={[0, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown045.geometry}
        material={nodes.shadeBrown045.material}
        position={[-11.44, 7.7, -0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown048.geometry}
        material={nodes.shadeBrown048.material}
        position={[-8.6, 0.33, -0.25]}
        rotation={[0, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown047.geometry}
        material={nodes.shadeBrown047.material}
        position={[-11.44, 0.33, -0.25]}
        rotation={[0, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown046.geometry}
        material={nodes.shadeBrown046.material}
        position={[-10.02, 0.46, 0.62]}
        rotation={[0, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown050.geometry}
        material={nodes.shadeBrown050.material}
        position={[-9.46, 9.91, 0.57]}
        rotation={[0, 0, Math.PI / 2]}
        scale={1.18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown055.geometry}
        material={nodes.shadeBrown055.material}
        position={[-10.82, -4.51, 0.57]}
        scale={1.18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown052.geometry}
        material={nodes.shadeBrown052.material}
        position={[-14.86, 7.93, 0.57]}
        scale={1.18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown051.geometry}
        material={nodes.shadeBrown051.material}
        position={[12.91, 8.4, 0.57]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown053.geometry}
        material={nodes.shadeBrown053.material}
        position={[-3.2, -1.43, 0.57]}
        rotation={[0, 0, Math.PI]}
        scale={1.18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeGreen007.geometry}
        material={nodes.shadeGreen007.material}
        position={[-3.2, -1.43, 1.27]}
        rotation={[0, 0, Math.PI]}
        scale={1.18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeGreen003.geometry}
        material={nodes.shadeGreen003.material}
        position={[-9.46, 9.91, 1.27]}
        rotation={[0, 0, Math.PI / 2]}
        scale={1.18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown054.geometry}
        material={nodes.shadeBrown054.material}
        position={[15.16, -12.14, 0.57]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeGreen004.geometry}
        material={nodes.shadeGreen004.material}
        position={[12.91, 8.4, 1.27]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeWhite_002002.geometry}
        material={nodes.shadeWhite_002002.material}
        position={[-2.26, 8.76, 0.02]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeGreen009.geometry}
        material={nodes.shadeGreen009.material}
        position={[15.16, -12.14, 1.27]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeGreen005.geometry}
        material={nodes.shadeGreen005.material}
        position={[-14.86, 7.93, 1.27]}
        scale={1.18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeGreen010.geometry}
        material={nodes.shadeGreen010.material}
        position={[-10.82, -4.51, 1.27]}
        scale={1.18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeWhite_015008.geometry}
        material={nodes.shadeWhite_015008.material}
        position={[-7.95, -2.29, 0]}
        scale={0.18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeWhite_003003.geometry}
        material={nodes.shadeWhite_003003.material}
        position={[13.74, 9.07, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeWhite_001002.geometry}
        material={nodes.shadeWhite_001002.material}
        position={[-3.97, -2.05, 0.03]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.81}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeWhite_004001.geometry}
        material={nodes.shadeWhite_004001.material}
        position={[11.27, 17.86, 0.02]}
        rotation={[0, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeWhite_015019.geometry}
        material={nodes.shadeWhite_015019.material}
        position={[12.29, 17.57, 0]}
        scale={0.16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeWhite_002003.geometry}
        material={nodes.shadeWhite_002003.material}
        position={[6.75, -2.12, 0.01]}
        rotation={[0, 0, Math.PI / 2]}
        scale={0.63}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeWhite_015006.geometry}
        material={nodes.shadeWhite_015006.material}
        position={[-1.34, 9.45, 0]}
        scale={0.16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeWhite_015022.geometry}
        material={nodes.shadeWhite_015022.material}
        position={[15.47, -12.55, 0]}
        scale={0.18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeWhite_015023.geometry}
        material={nodes.shadeWhite_015023.material}
        position={[15.9, -12.28, 0]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.27, 0.27, 0.18]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_023.geometry}
        material={nodes.shadeBrown_023.material}
        position={[0.71, -6.01, 0.09]}
        rotation={[Math.PI / 2, 0, -0.82]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeWhite_015018.geometry}
        material={nodes.shadeWhite_015018.material}
        position={[14.86, 8.86, 0]}
        scale={0.16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeWhite_015025.geometry}
        material={nodes.shadeWhite_015025.material}
        position={[4.38, 0.13, 0]}
        rotation={[0, 0, Math.PI]}
        scale={0.16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeWhite_015021.geometry}
        material={nodes.shadeWhite_015021.material}
        position={[11.5, 0.62, 0]}
        scale={0.16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_020001.geometry}
        material={nodes.shadeBrown_020001.material}
        position={[0.4, -14.78, 0.12]}
        rotation={[0, -1.03, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeWhite_015020.geometry}
        material={nodes.shadeWhite_015020.material}
        position={[11.25, 0.82, 0]}
        scale={0.16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_018.geometry}
        material={nodes.shadeBrown_018.material}
        position={[0.64, -4.94, 0.42]}
        rotation={[0, -0.79, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_019.geometry}
        material={nodes.shadeBrown_019.material}
        position={[0.27, -4.94, 0.1]}
        rotation={[0, -0.79, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBeige_002.geometry}
        material={nodes.shadeBeige_002.material}
        position={[1.05, -14.93, 0.17]}
        rotation={[0, -0.22, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeWhite_015024.geometry}
        material={nodes.shadeWhite_015024.material}
        position={[6.04, -2.81, 0]}
        rotation={[0, 0, Math.PI]}
        scale={0.16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_021.geometry}
        material={nodes.shadeBrown_021.material}
        position={[0.4, -4.07, 0.32]}
        rotation={[0, -0.7, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_022.geometry}
        material={nodes.shadeBrown_022.material}
        position={[0.4, -5.84, 0.32]}
        rotation={[0, -0.7, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBeige_003.geometry}
        material={nodes.shadeBeige_003.material}
        position={[6.45, -9.9, 0.12]}
        rotation={[0, -0.34, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBeige_001.geometry}
        material={nodes.shadeBeige_001.material}
        position={[1.13, -5.09, 0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_018001.geometry}
        material={nodes.shadeBrown_018001.material}
        position={[0.6, -14.78, 0.29]}
        rotation={[0, -1.12, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_019001.geometry}
        material={nodes.shadeBrown_019001.material}
        position={[0.47, -14.78, -0.03]}
        rotation={[0, -1.12, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_015002.geometry}
        material={nodes.shadeBrown_015002.material}
        position={[3.54, -8.84, 0.74]}
        rotation={[0, -1.13, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_020.geometry}
        material={nodes.shadeBrown_020.material}
        position={[0.4, -4.94, 0.32]}
        rotation={[0, -0.7, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_022001.geometry}
        material={nodes.shadeBrown_022001.material}
        position={[0.4, -15.68, 0.12]}
        rotation={[0, -1.03, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_014001.geometry}
        material={nodes.shadeBrown_014001.material}
        position={[0.91, -15.88, 0.1]}
        rotation={[Math.PI / 2, 0, -2.06]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_017006.geometry}
        material={nodes.shadeBrown_017006.material}
        position={[3.58, -9.77, 0.61]}
        rotation={[0, -1.12, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_014.geometry}
        material={nodes.shadeBrown_014.material}
        position={[0.79, -6.11, 0.14]}
        rotation={[Math.PI / 2, 0, -1.56]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_017003.geometry}
        material={nodes.shadeBrown_017003.material}
        position={[5.25, -9.79, 0.61]}
        rotation={[0, 0.43, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_017004.geometry}
        material={nodes.shadeBrown_017004.material}
        position={[5.25, -8.52, 0.61]}
        rotation={[0, 0.43, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_017010.geometry}
        material={nodes.shadeBrown_017010.material}
        position={[4.57, -11.15, -0.11]}
        rotation={[Math.PI / 2, 0, -1.94]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_021001.geometry}
        material={nodes.shadeBrown_021001.material}
        position={[0.4, -13.91, 0.12]}
        rotation={[0, -1.03, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBeige_006.geometry}
        material={nodes.shadeBeige_006.material}
        position={[4.49, -9.9, 1.07]}
        rotation={[0, -0.34, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_015001.geometry}
        material={nodes.shadeBrown_015001.material}
        position={[3.54, -9.49, 0.74]}
        rotation={[0, -1.13, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_017012.geometry}
        material={nodes.shadeBrown_017012.material}
        position={[-5.99, -9.73, 0.61]}
        rotation={[0, -0.43, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_017002.geometry}
        material={nodes.shadeBrown_017002.material}
        position={[5.25, -10.97, 0.61]}
        rotation={[0, 0.43, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_017005.geometry}
        material={nodes.shadeBrown_017005.material}
        position={[3.77, -9.77, 1.05]}
        rotation={[0, -1.12, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_015004.geometry}
        material={nodes.shadeBrown_015004.material}
        position={[3.54, -10.09, 0.74]}
        rotation={[0, -1.13, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBeige_009.geometry}
        material={nodes.shadeBeige_009.material}
        position={[-5.23, -9.62, 1.07]}
        rotation={[0, 0.34, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBeige_005.geometry}
        material={nodes.shadeBeige_005.material}
        position={[5.47, -9.9, 0.6]}
        rotation={[0, -0.34, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_017008.geometry}
        material={nodes.shadeBrown_017008.material}
        position={[4.87, -11.15, 0.53]}
        rotation={[Math.PI / 2, 0, -2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_017009.geometry}
        material={nodes.shadeBrown_017009.material}
        position={[4.72, -11.15, 0.19]}
        rotation={[Math.PI / 2, 0, -2.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_015008.geometry}
        material={nodes.shadeBrown_015008.material}
        position={[-4.28, -9.43, 0.74]}
        rotation={[0, 1.13, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_015003.geometry}
        material={nodes.shadeBrown_015003.material}
        position={[3.54, -10.72, 0.74]}
        rotation={[0, -1.13, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_016002.geometry}
        material={nodes.shadeBrown_016002.material}
        position={[3.94, -11.27, 0.42]}
        rotation={[-Math.PI / 2, 0, 0.76]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_017011.geometry}
        material={nodes.shadeBrown_017011.material}
        position={[-5.99, -8.54, 0.61]}
        rotation={[0, -0.43, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_017017.geometry}
        material={nodes.shadeBrown_017017.material}
        position={[-5.61, -11.18, 0.53]}
        rotation={[-Math.PI / 2, 0, 1.14]}
        scale={[1, 1, -1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_017007.geometry}
        material={nodes.shadeBrown_017007.material}
        position={[3.38, -9.77, 0.19]}
        rotation={[0, -1.12, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBeige_008.geometry}
        material={nodes.shadeBeige_008.material}
        position={[-6.21, -9.62, 0.6]}
        rotation={[0, 0.34, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBeige_007.geometry}
        material={nodes.shadeBeige_007.material}
        position={[-7.19, -9.62, 0.12]}
        rotation={[0, 0.34, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_016004.geometry}
        material={nodes.shadeBrown_016004.material}
        position={[-4.68, -11.3, 0.42]}
        rotation={[Math.PI / 2, 0, -2.38]}
        scale={[1, 1, -1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_016001.geometry}
        material={nodes.shadeBrown_016001.material}
        position={[4.52, -11.27, 0.48]}
        rotation={[-Math.PI / 2, 0, -0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_015007.geometry}
        material={nodes.shadeBrown_015007.material}
        position={[-4.28, -8.8, 0.74]}
        rotation={[0, 1.13, 1.64]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_015006.geometry}
        material={nodes.shadeBrown_015006.material}
        position={[-4.28, -10.68, 0.74]}
        rotation={[0, 1.13, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown059.geometry}
        material={nodes.shadeBrown059.material}
        position={[-0.17, -9.67, 0.57]}
        scale={1.18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_017013.geometry}
        material={nodes.shadeBrown_017013.material}
        position={[-5.99, -11, 0.61]}
        rotation={[0, -0.43, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_017016.geometry}
        material={nodes.shadeBrown_017016.material}
        position={[-4.12, -9.73, 0.19]}
        rotation={[0, 1.12, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_017015.geometry}
        material={nodes.shadeBrown_017015.material}
        position={[-4.32, -9.73, 0.61]}
        rotation={[0, 1.12, -3.09]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_015005.geometry}
        material={nodes.shadeBrown_015005.material}
        position={[-4.28, -10.03, 0.74]}
        rotation={[0, 1.13, 1.49]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_016003.geometry}
        material={nodes.shadeBrown_016003.material}
        position={[-5.26, -11.3, 0.48]}
        rotation={[Math.PI / 2, 0, 3.11]}
        scale={[1, 1, -1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_017019.geometry}
        material={nodes.shadeBrown_017019.material}
        position={[-5.31, -11.18, -0.11]}
        rotation={[-Math.PI / 2, 0, 1.2]}
        scale={[1, 1, -1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_017014.geometry}
        material={nodes.shadeBrown_017014.material}
        position={[-4.51, -9.73, 1.05]}
        rotation={[0, 1.12, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeRed_004.geometry}
        material={nodes.shadeRed_004.material}
        position={[-0.17, -8.54, 2.46]}
        scale={1.18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeRed_003.geometry}
        material={nodes.shadeRed_003.material}
        position={[-0.17, -10.81, 2.46]}
        scale={1.18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBrown_017018.geometry}
        material={nodes.shadeBrown_017018.material}
        position={[-5.46, -11.18, 0.19]}
        rotation={[-Math.PI / 2, 0, 1.1]}
        scale={[1, 1, -1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shadeBeige.geometry}
        material={nodes.shadeBeige.material}
        position={[-0.17, -9.67, 1.33]}
        scale={1.18}
      />
    </group>
  );
}

useGLTF.preload("/base.glb");
